let a = 3;
let b = 4;
try {
  console.log(a + c);
} catch (err) {
  console.log(err);
}
